### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by tjingboem** [gogins/csound-ac#34]
In my Linux system, I copied the CsoundAC files over as Linux release from mentionedhttps://github.com/gogins/csound-ac/releases mentions. This is version 5 from March 20th. Then **sudo ldconfig**

After that i copy the ac-reaper.py file to ~/config/REAPER/Scripts
In the Actions window form Reaper, a Python file, unlike lua or eel is not seen. So i switch to All Files and doubleclick ac-reaper.py

![Screenshot from 2024-12-29 12-22-50](https://github.com/user-attachments/assets/7c9b661d-7ff1-4af1-a12f-3333eeec748e)

![Screenshot from 2024-12-29 12-24-48](https://github.com/user-attachments/assets/b7619759-2cc4-4a9a-b3e0-d8d579bdb5ec)

First: i am unsure if CsoundAC is installed correctly
Second: what should be done in the script so that CsoundAC runs within Reaper?

**Comment by tjingboem** [comment]
i just now added a PYTHONPATH
PYTHONPATH=/usr/local/lib/python3.12/dist-packages
and copied CsoundAC.py to that place
did not work

**Comment by gogins** [comment]
First, right now there is a binary release of CsoundAC only for macOS and
only for Python 3.12. If you build CsoundAC yourself, you need to make a
note of which Python is used.

You can run python3, python3.12, etc., and see which version of Python will
succeed in importing CsoundAC.

Second, you need to make sure that Reaper uses that specific version of
Python. There is a Reaper setting for that:

[image: image.png]

I hope you attend the Zoom meeting tomorrow.

Best,
Mike
-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by tjingboem** [comment]
So the development build from https://github.com/gogins/csound-ac/releases
does not work?

It does have the same version number as the MacOS one.

**Comment by gogins** [comment]
I'm talking about the Python version number, not the CsoundAC version
number. What operating system are you using?

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by tjingboem** [comment]
i see you are replying via mail, not via Github
i have written more information via Github but that will not show up via
the mail.
And the image you posted does not show, it is a screenshot of Reaper i
presume.

So i will start using the mail for a resumé.
Linux Mint 22, Python 3.12.3

**Comment by gogins** [comment]
CsoundAC consists of two files, a native shared library _CsoundAC.so (on
Linux, .dlyd on macOS) and a Python file. Both of these files should be in
the site-packages directory for the correct version of Python, which must
be the version against which the .so file was built.

On my MacBook Pro, these files are:

/opt/homebrew/lib/python3.12/site-packages/CsoundAC.py
/opt/homebrew/lib/python3.12/site-packages/_CsoundAC.so

To test the installation, I go to the command line and run Python, then I
manually import CsoundAC.

If I try with the wrong version of Python, I get an error:

***@***.*** ~ % python3
Python 3.13.1 (main, Dec  3 2024, 17:59:52) [Clang 16.0.0
(clang-1600.0.26.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import CsoundAC
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import CsoundAC
ModuleNotFoundError: No module named 'CsoundAC'

If I try with the correct version of Python, there is no error:

***@***.*** ~ % python3.12
Python 3.12.8 (main, Dec  3 2024, 18:42:41) [Clang 16.0.0
(clang-1600.0.26.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import CsoundAC
>>>

Then in Reaper, I ensure that the Python version used for ReaScript is the
same as the Python version that successfully imports CsoundAC:

[image: image.png]

The key here is that Reaper says "libpython3.12.dylib is installed". On
Linux, that would be libpython3.12.so. You need to find where that library
is on your system, and copy the full pathname of that file into the "Custom
path" field here.

Of course on your Linux machine the version of Python could be 3.9, 3.10
3.11, or whatever.  I don't recall any more what version of Python it was,
but I think you can find out by executing "ldd _CsoundAC.so" (fill pathname
of _CsoundAC.so will be required) and seeing what Python library has been
linked with CsoundAC.

Sorry this is so complex....

Best,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by tjingboem** [comment]
Thanks for your elaborate reply.
Yes, it is complex. I'd like to cut this up into little steps to see where
things go wrong.

First little step:

On Thu, Jan 2, 2025 at 10:52 AM Michael Gogins ***@***.***>
wrote:

> CsoundAC consists of two files, a native shared library _CsoundAC.so (on
> Linux, .dlyd on macOS) and a Python file. Both of these files should be in
> the site-packages directory for the correct version of Python, which must
> be the version against which the .so file was built.
>
>
I did not build anything. Should I?
In the instructions on https://github.com/gogins/csound-ac i read this:
 There are prebuilt binary releases for this package available at
https://github.com/gogins/csound-ac/releases.

 So i was glad that there are binary releases and chose from
https://github.com/gogins/csound-ac/releases the Linux Development Release.
This is from March but is has the same release number 0.50 as the Mac
release. Although the Mac release is from November.

Is this not the Linux build i should use?

**Comment by gogins** [comment]
it should be usable.

**Comment by tjingboem** [comment]
a few days ago i copied _CsoundAC.so and CsoundAC.py over to several locations- among them to 
/usr/local/lib/python3.12/dist-packages

I do not have other Python versions installed.

This is what happens:
```

tjingboem@tjingboemKOMP ~ $ python3.12
Python 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import CsoundAC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/dist-packages/CsoundAC.py", line 15, in <module>
    import _CsoundAC
ImportError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
>>> 
```
![Screenshot from 2025-01-02 12-40-38](https://github.com/user-attachments/assets/be53b75d-44c7-4852-a6f4-daaaec18a260)

**Comment by gogins** [comment]
This means that your _CsoundAC.so shared library was linked to
libpython3.10.so.1.0. If you install Python3.10, install CsoundAC in
Python3.10's site-packages, and run python3.10 it should work.

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by tjingboem** [comment]
i do not have libpython3.10.so.1.0 on my computer.
I do have libpython3.12.so.1.0

![Screenshot from 2025-01-02 13-08-21](https://github.com/user-attachments/assets/e2033134-65e0-4f64-9267-ce4497b03261)

Is there something in _CsoundAC.so that i can change to make it point to libpython3.12.so.1.0 ?

**Comment by tjingboem** [comment]
it seems i can not install 3.10 as it will break the system.

I will be so courageous and build against 3.12 tomorrow :)

**Comment by gogins** [comment]
OK! I'm available if you want help.

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by tjingboem** [comment]
thank you very much.

**Comment by gogins** [comment]
I wonder if LaTeX on @tjingboem's system has `restricted \write18 enabled.`

**Comment by gogins** [comment]
I have removed all dependencies on OpenCV libraries from CsoundAC. Image processing is now done using only open source, header-file-only libraries, namely stb-image and CImg.

**Comment by tjingboem** [comment]
I would like to rebuild CsoundAC for Linux Mint, using these new libraries.

stb-image is not in Synaptic, but i found stb here:
https://github.com/nothings/stb/tree/master
There i find stb_image.h. What should i do with it?

In Synaptic i found cimg-dev 3.2.1.

**Comment by tjingboem** [comment]
i have libsndfile1-dev installed, but get an error when building? 
Hope you might be able to help:

tjingboem@tjingboemKOMP ~/csound-ac/build-linux $ cmake -Wno-dev .. -DCMAKE_PREFIX_PATH=/usr/local:/usr
-- The C compiler identification is GNU 13.3.0
-- The CXX compiler identification is GNU 13.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Doxygen: /bin/doxygen (found version "1.9.8") found components: doxygen dot
CMAKE BUILD SYSTEM FOR CSOUND-AC
For a fresh build, run 'bash fresh-build-linux.sh'
CSOUND_AC_CUSTOM_CONFIGURATION: NOTFOUND
-- CMAKE_MODULE_PATH: /home/tjingboem/csound-ac/cmake/Modules;/home/tjingboem/csound-ac/dependencies/csound/cmake/Modules
-- CMAKE_INSTALL_PREFIX: /usr/local
-- CPACK_PACKAGING_INSTALL_PREFIX: 
-- BUILD_BIN_DIR: /home/tjingboem/csound-ac/build-linux
-- BUILD_LIB_DIR: /home/tjingboem/csound-ac/build-linux
-- LIBRARY INSTALL DIR: lib
-- PLUGIN_INSTALL_DIR: 
CMAKE_SYSTEM_NAME: Linux
-- CSOUND_LIBRARY (missing: CSOUND_INCLUDE_DIR) 
CSOUND_LIBRARIES: /usr/local/lib/libcsound64.so
CSOUND_INCLUDE_DIRS: CSOUND_INCLUDE_DIR-NOTFOUND
CSOUND_INCLUDE_PATH: 
CMake Error at CMakeLists.txt:88 (find_package):
  By not providing "FindSndFile.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SndFile", but
  CMake did not find one.

  Could not find a package configuration file provided by "SndFile" with any
  of the following names:

    SndFileConfig.cmake
    sndfile-config.cmake

  Add the installation prefix of "SndFile" to CMAKE_PREFIX_PATH or set
  "SndFile_DIR" to a directory containing one of the above files.  If
  "SndFile" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!

**Comment by gogins** [comment]
I removed the OpenCV dependency. The Linux release and build seem to be working now.
